### ISSUE TITLE
Trocar pin do usuário no mapa

### ISSUE THREAD

**Issue by pmarkun** [LabHackerSP/comidaimigrante#13]

**Comment by alencargu** [comment]
![pin](https://cloud.githubusercontent.com/assets/16898448/24218309/8782ded0-0f21-11e7-9c24-7314a57e1b3c.png)
![pin2](https://cloud.githubusercontent.com/assets/16898448/24218308/8781c7f2-0f21-11e7-8aa2-c66c7a5c2e34.png)

**Comment by alencargu** [comment]
![pin3](https://cloud.githubusercontent.com/assets/16898448/24219338/2cbcc584-0f25-11e7-8240-36c3950ffcea.png)

**Comment by alencargu** [comment]
@pmarkun Segue o pin

**Comment by Lana-chan** [comment]
resolvido em fe8e83dca949f29c14f9b6123b44250183ac65c8
