### ISSUE TITLE
implementar visitaço

### ISSUE THREAD

**Issue by Lana-chan** [LabHackerSP/comidaimigrante#3]
definir o que É um visitaço, etc

**Comment by pmarkun** [comment]
1) Qualquer usuário logado pode criar um visitaço.
2) A chave primaria do usuário é seu número de celular, puxado via api do Cordova.
3) O usuário pode dizer se quer que o Evento (Visitaço) seja público ou privado.
4) Em caso de visitaço público - ele aparece sempre no restaurante associado.
5) Em caso de visitaço privado - ele só aparece para o usuário que estiver na lista de contatos do usuário criador.

**Comment by Lana-chan** [comment]
implementação terminada em 0f2d15618582e7406360b2f7caba6599944a1126
